repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

default_language_version:
  python: python3.12

exclude: |
  (?x)^(
    \.git/|
    \.venv/|
    \.pytest_cache/|
    \.mypy_cache/|
    \.ruff_cache/|
    __pycache__/|
    \.ipynb_checkpoints/|
    build/|
    dist/|
    .*\.egg-info/|
    uv\.lock|
    reports/
  )$

fail_fast: false
